[tool.poetry]
name = "magichat"
version = "0.1.0"
description = "Funsies"
authors = ["ethan <ethan.lee.zhu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]

